name: Build

on:
  workflow_call:
    inputs:
      update_version_command:
        required: false
        type: string
        default: npm version patch
      update_version:
        required: true
        type: boolean
        default: true
      branch:
        required: false
        type: string
        default: ${{ github.ref }}

    secrets:
      GH_PAT:
        description: 'needed for github login'
        required: true
      GPG_PRIVATE_KEY2:
        description: 'needed for gpg key'
        required: true
      GPG_KEY_ID:
        description: 'needed for gpg key'
        required: true
      UNS_API_KEY:
        description: 'needed for uns'
        required: true
      SIMPLE_HASH_API_KEY:
        description: 'needed for simple hash'
        required: true
      ZEROX_API_KEY:
        description: 'needed for zerox'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          ssh-key: ${{ secrets.GH_PAT }}

      - name: Import GPG Key
        if: ${{ inputs.update_version }}
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY2 }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import
          git config --global user.signingkey $GPG_KEY_ID
          git config --global commit.gpgsign true
          # Configure Git with CI account details
          git config --global user.name "ci-dominantstrategies"
          git config --global user.email "ci@dominantstrategies.io"
          
          # Optionally, check that the GPG key is correctly configured for signing
          gpg --list-keys "ci@dominantstrategies.io"

      - name: Install yq
        run: sudo snap install yq

      - name: get Version
        run: |
          VERSION_VALUE=$(sudo yq eval '.version' package.json | head -n 1)
          echo "VERSION=$VERSION_VALUE"
          echo "VERSION=$VERSION_VALUE" >> $GITHUB_ENV

      - name: git tag
        if: ${{ inputs.update_version }}
        run: git tag ${{ env.VERSION }} && HUSKY=0 git push origin tag ${{ env.VERSION }}

  build:
    runs-on: ubuntu-latest
    needs: [tag]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_PAT }}

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY2 }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import
          git config --global user.signingkey $GPG_KEY_ID
          git config --global commit.gpgsign true

          # Configure Git with CI account details
          git config --global user.name "ci-dominantstrategies"
          git config --global user.email "ci@dominantstrategies.io"

          # Optionally, check that the GPG key is correctly configured for signing
          gpg --list-keys "ci@dominantstrategies.io"

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat ./.nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Use Node + Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - name: Detect env block
        id: env-block
        if: ${{ !inputs.update_version }}
        uses: actions/github-script@v6
        with:
          script: |
            const detectEnvBlock = require("./.github/workflows/builds/detect-env-block.js")
            return await detectEnvBlock({ github, context })
      - name: Dev build
        if: ${{ !inputs.update_version }}
        run: |
          echo -e ${{ steps.env-block.outputs.result }} > .env
          echo 'USE_ANALYTICS_SOURCE="BETA"' >> .env
          yarn build
        env:
          COMMIT_SHA: ${{ github.sha }}
      - name: Production build
        if: ${{ inputs.update_version }}
        run: |
          echo 'USE_ANALYTICS_SOURCE="PROD"' >> .env
          yarn build
        env:
          UNS_API_KEY: ${{ secrets.UNS_API_KEY }}
          SIMPLE_HASH_API_KEY: ${{ secrets.SIMPLE_HASH_API_KEY }}
          ZEROX_API_KEY: ${{ secrets.ZEROX_API_KEY }}
          COMMIT_SHA: ${{ github.sha }}
      - name: Upload build asset
        if: ${{ inputs.update_version }}
        uses: actions/upload-artifact@v3
        with:
          name: extension-builds-${{ github.event.number || github.event.head_commit.id }}
          path: dist/*.zip
      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # v1
        if: ${{ inputs.update_version }}
        with:
          files: dist/*.zip
          draft: true
          generate_release_notes: true
          prerelease: false
      - name: Install jq
        if: ${{ inputs.update_version }}
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: install semver globally
        if: ${{ inputs.update_version }}
        run: npm install -g semver
      - name: Update Version
        if: ${{ inputs.update_version }}
        run: ${{ inputs.update_version_command }}
      - name: get Version
        if: ${{ inputs.update_version }}
        run: |
          VERSION_VALUE=$(sudo yq eval '.version' package.json | head -n 1)
          echo "VERSION=$VERSION_VALUE"
          echo "VERSION=$VERSION_VALUE" >> $GITHUB_ENV
      - name: Sync Versions
        if: ${{ inputs.update_version }}
        run: |
          yq eval -i ".dependencies.@pelagus/pelagus-background = \"${{ env.VERSION }}\"" package.json
          yq eval -i ".dependencies.@pelagus/pelagus-ui = \"${{ env.VERSION }}\"" package.json
          yq eval -i ".dependencies.@tallyho/provider-bridge = \"${{ env.VERSION }}\"" package.json
          yq eval -i ".dependencies.@tallyho/provider-bridge-shared = \"${{ env.VERSION }}\"" package.json
          yq eval -i ".dependencies.@tallyho/window-provider = \"${{ env.VERSION }}\"" package.json
          yq eval -i ".dependencies.@tallyho/provider-bridge-shared = \"${{ env.VERSION }}\"" provider-bridge/package.json
          yq eval -i ".dependencies.@pelagus/pelagus-background = \"${{ env.VERSION }}\"" provider-bridge/package.json
          yq eval -i ".dependencies.@pelagus/pelagus-background = \"${{ env.VERSION }}\"" ui/package.json
          yq eval -i ".dependencies.@tallyho/provider-bridge-shared = \"${{ env.VERSION }}\"" window-provider/package.json
          yq eval -i ".dependencies.@tallyho/provider-bridge-shared = \"${{ env.VERSION }}\"" background/package.json
          yq eval -i ".dependencies.@tallyho/provider-bridge-shared = \"${{ env.VERSION }}\"" ui/package.json
          yq eval -i ".dependencies.@tallyho/window-provider = \"${{ env.VERSION }}\"" background/package.json
          yq eval -i ".version = \"${{ env.VERSION }}\"" provider-bridge/package.json
          yq eval -i ".version = \"${{ env.VERSION }}\"" provider-bridge-shared/package.json
          yq eval -i ".version = \"${{ env.VERSION }}\"" window-provider/package.json
          yq eval -i ".version = \"${{ env.VERSION }}\"" background/package.json
          yq eval -i ".version = \"${{ env.VERSION }}\"" ui/package.json
          STRIPPED_VERSION=$(echo "${{ env.VERSION }}" | tr -d '"' | sed -e 's/^v//' -e 's/-[^0-9.]*$//')
          yq eval -i ".version = \"${STRIPPED_VERSION}\"" manifest/manifest.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ inputs.update_version }}
        with:
          branch: ${{ inputs.branch }}
          commit_user_name: ci-dominantstrategies
          commit_user_email: ci@dominantstrategies.io
        env:
          HUSKY: 0



  ## test:
  ##   runs-on: ubuntu-latest
  ##   steps:
  ##     - uses: actions/checkout@v3
  ##     - name: Read .nvmrc
  ##       run: echo "NVMRC=$(cat ./.nvmrc)" >> $GITHUB_OUTPUT
  ##       id: nvm
  ##     - name: Use Node + Yarn
  ##       uses: actions/setup-node@v3
  ##       with:
  ##         node-version: "${{ steps.nvm.outputs.NVMRC }}"
  ##         cache: "yarn"
  ##     - run: yarn install --frozen-lockfile
  ##     - run: yarn test
  ## lint:
  ##   runs-on: ubuntu-latest
  ##   steps:
  ##     - uses: actions/checkout@v3
  ##     - name: Read .nvmrc
  ##       run: echo "NVMRC=$(cat ./.nvmrc)" >> $GITHUB_OUTPUT
  ##       id: nvm
  ##     - name: Use Node + Yarn
  ##       uses: actions/setup-node@v3
  ##       with:
  ##         node-version: "${{ steps.nvm.outputs.NVMRC }}"
  ##         cache: "yarn"
  ##     - run: yarn install --frozen-lockfile
  ##     - run: yarn lint
  detect-if-flag-changed:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            path-filter:
              - '.env.defaults'
  ## e2e-tests:
  ##   if: |
  ##     github.ref == 'refs/heads/main'
  ##       || contains(github.head_ref, 'e2e')
  ##       || needs.detect-if-flag-changed.outputs.path-filter == 'true'
  ##   needs: [build, detect-if-flag-changed]
  ##   timeout-minutes: 60
  ##   runs-on: ubuntu-latest
  ##   steps:
  ##     - uses: actions/checkout@v3
  ##     - name: Read .nvmrc
  ##       run: echo "NVMRC=$(cat ./.nvmrc)" >> $GITHUB_OUTPUT
  ##       id: nvm
  ##     - name: Use Node + Yarn
  ##       uses: actions/setup-node@v3
  ##       with:
  ##         node-version: "${{ steps.nvm.outputs.NVMRC }}"
  ##         cache: "yarn"
  ##     - run: yarn install --frozen-lockfile
  ##     - name: Install Playwright Browsers
  ##       run: npx playwright install --with-deps chromium
  ##     - uses: actions/download-artifact@v3
  ##       with:
  ##         name: extension-builds-${{ github.event.number || github.event.head_commit.id }}
  ##     - name: Extract extension
  ##       run: unzip -o chrome.zip -d dist/chrome
  ##     - name: Run Playwright tests
  ##       run: xvfb-run npx playwright test
  ##       #env:
  ##       # DEBUG: pw:api*
  ##     - uses: actions/upload-artifact@v3
  ##       if: failure()
  ##       with:
  ##         name: debug-output
  ##         path: |
  ##           test-results/
  ##           #videos/
  ##         retention-days: 30
