name: Build Dev
on:
  pull_request:
    types: [closed]
    branches: ["main"]
jobs:
  buildDeployDev:
    uses: ./.github/workflows/build.yml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      GPG_PRIVATE_KEY2: ${{ secrets.GPG_PRIVATE_KEY2 }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
    with:
      update_version_command: npm version prerelease --preid=pre --no-git-tag-version
      update_version: false
