name: Patch
on: workflow_dispatch
jobs:
  buildDeployDev:
    uses: ./.github/workflows/build.yml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      GPG_PRIVATE_KEY2: ${{ secrets.GPG_PRIVATE_KEY2 }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      UNS_API_KEY: ${{ secrets.UNS_API_KEY }}
    with:
      update_version_command: 'jq --arg new_version "$(npx semver -i patch $(jq -r ''.version'' package.json | sed ''s/^v//''))" ''.version = $new_version'' package.json > temp.json && mv temp.json package.json'
      update_version: true
