name: Post build link

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        type: string
        description: "The id of a workflow run to dispatch off of."
        required: true
  workflow_run:
    workflows:
      - Build
      - Build-Manual
    types:
      - completed

jobs:
  post-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_PAT }}

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import
          git config --global user.signingkey $GPG_KEY_ID
          git config --global commit.gpgsign true

          # Configure Git with CI account details
          git config --global user.name "ci-dominantstrategies"
          git config --global user.email "ci@dominantstrategies.io"

          # Optionally, check that the GPG key is correctly configured for signing
          gpg --list-keys "ci@dominantstrategies.io"

      - name: Post artifact link to PR if available
        uses: actions/github-script@v6
        with:
          script: |
            const postBuildLink = require("./.github/workflows/builds/post-build-link.js")
            await postBuildLink({ github, context })
